apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: devops-intermidate
  labels:
    app: html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: 768722692321.dkr.ecr.us-east-2.amazonaws.com/my-ecr-repo:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: owner
          value: Hamo
        ports:
        - containerPort: 80
