apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops-intermidate
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "delete", "watch","list"]
